### ISSUE TITLE
PHP parsing error when trying to install the plugin

### ISSUE THREAD

**Issue by paulo-graca** [publons/ojs_2_plugin#7]
The problem occurs on line 230:

```
$eas = $templateMgr->get_template_vars()['submission']->getEditAssignments();
```

When trying to install the schema:
```
# php tools/dbXMLtoSQL.php -schema execute /ojs/ojs-2.4.8-2/plugins/generic/publons/schema.xml
```

The error message is:
```
PHP Parse error:  syntax error, unexpected '[' in /ojs/ojs-2.4.8-2/plugins/generic/publons/PublonsPlugin.inc.php on line 230
```

My PHP version:
```
# php -v
PHP 5.3.3 (cli) (built: Aug 11 2016 20:33:53)
```

**Comment by mark-cameron** [comment]
This error is most likely caused due to the use of PHP 5.3.

Looking at the read-me in the requirements it does say a minimum of 5.2 which is a mistake and has now been changed.

Very sorry about that confusion, is it easy for you to update to 5.6, as 5.3 is long out of date (stopped being supported in 2014)?
